### ISSUE TITLE
Capture image too large error

### ISSUE THREAD

**Issue by gjwgit** [gjwgit/azcv#1]
Capture this error and either reduce the image size seamlessly or at least ask the user to do so and include an example of how to reduce the image size using imagemagick.

```
Traceback (most recent call last):
  File "tags.py", line 71, in <module>
    analysis = client.analyze_image_in_stream(fstream, visual_features=[VisualFeatureTypes.tags])
  File "/home/kayon/.mlhub/azcv/.python/home/kayon/.local/lib/python3.7/site-packages/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py", line 1047, in analyze_image_in_stream
    raise models.ComputerVisionErrorException(self._deserialize, response)
azure.cognitiveservices.vision.computervision.models._models_py3.ComputerVisionErrorException: Input image is too large.
Traceback (most recent call last):
  File "/home/kayon/.local/bin/ml", line 10, in <module>
    sys.exit(main())
  File "/home/kayon/.local/lib/python3.7/site-packages/mlhub/__init__.py", line 197, in main
    args.func(args)
  File "/home/kayon/.local/lib/python3.7/site-packages/mlhub/commands.py", line 1041, in dispatch
    errors = errors.decode("utf-8")
AttributeError: 'NoneType' object has no attribute 'decode'

```

**Comment by gjwgit** [comment]
The command line to reduce image size:

```
$ wajig install imagemagick
$ convert bigimg.jpg -resize 25% smallerimg.jpg
```

**Comment by gjwgit** [comment]
Error message now captured and suggestion made. Commit 1beba9f3de60134b2af46b2ac4333a11a7966d4e Version 2.5.2
